### ISSUE TITLE
代码底层判断问题

### ISSUE THREAD

**Issue by LL-MF** [Echox1/windows_baseline#1]
感谢带来的思路，但windows基线检测代码运行结果并不可靠，powershell中的条件操作符如-ge(大于等于)在比较中会分和字符串的比较以及数字的比较。由于代码中未考虑该问题，采用$a[1]的形式截取数据，此时的比较会变为字符串型的比较，从而变成逐位比较而非我们寻常理解的数值大小比较，例如"7" -ge "12"，正常判断来说该比较会返回false，但是由于加了双引号从而变成字符串型的运算关系，7先和1比，此时返回的是true。例如第173行代码if($config_line[1] -ge "10")，此时$config_line[1]的类型为String，若$config_line[1]=3，此时运算结果会返回true，显然不是我们想要的答案
具体如下：
ps >>$config_line[1].GetType()

IsPublic IsSerial Name                                     BaseType            
——————————————————————————       
True     True     String                                   System.Object

ps >>$config_line[1] = 5
ps >>$config_line[1]
5
ps >> $config_line[1] -ge "10"
True

可以考虑修改为如下形式
[int]$config_line[1] -ge 10
具体如下
ps >>$config_line[1] = 5
ps >> [int]$config_line[1] -ge 10
False
$config_line[1] -ge 10
True

**Comment by Echox1** [comment]
感谢你的issue，当时代码要的的太急了没有注意到这个问题，我会抽时间修复这个问题。
